export const ADICIONAR_PROJETO =  'ADICIONAR_PROJETO'
export const ALTERAR_PROJETO =  "ALTERAR_PROJETO"
export const EXCLUIR_PROJETO =  "EXCLUIR_PROJETO"
export const DEFINIR_PROJETOS =  "DEFINIR_PROJETOS"

export const NOTIFICAR  = "NOTIFICAR"

export const DEFINIR_TAREFAS =  "DEFINIR_TAREFAS"
export const ADICIONA_TAREFA = "ADICIONA_TAREFA"
export const ALTERA_TAREFA = "ALTERA_TAREFA"